name: build-wasm

on:
  push:
    branches:
      - main
    paths:
      - "vendor/**"
      - "transpiler/**"
      - "wasm_binding/**"
      - ".github/workflows/build-wasm.yml"
  pull_request:
    branches:
      - main
    paths:
      - "vendor/**"
      - "transpiler/**"
      - "wasm_binding/**"
      - ".github/workflows/build-wasm.yml"

env:
  VERSION: 0.1.${{ github.run_number }}

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2024-04-16
            override: true
            components: rust-src

      - name: Build
        run: |
          cd wasm_binding && wasm-pack build --target web --release

      - name: version
        run: |
          echo ${VERSION}>wasm_binding/pkg/version.txt

      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: wasm_binding/pkg