name: deploy-all
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [build-docs]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          name: docs
          workflow: build-docs.yml

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v4
        with:
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4